import type { PlaygroundInput } from '../types/index.js';
import prisma from '../utils/prisma.js';

export class PlaygroundService {
  async executePrompt(input: PlaygroundInput, userId: string) {
    // Log usage
    await prisma.usageLog.create({
      data: {
        userId,
        module: 'PLAYGROUND',
        cost: 0,
        meta: {
          promptLength: input.prompt.length,
          variablesCount: input.variables ? Object.keys(input.variables).length : 0,
        },
      },
    });

    let processedPrompt = input.prompt;

    if (input.variables) {
      for (const [key, value] of Object.entries(input.variables)) {
        processedPrompt = processedPrompt.replace(new RegExp(`{{${key}}}`, 'g'), value);
      }
    }

    const mockResponses = [
      `Based on your prompt, here's a thoughtful response:\n\n"${processedPrompt.slice(0, 50)}..." is an interesting starting point. Let me elaborate on this concept and provide you with actionable insights.\n\n**Analysis:**\nThis prompt appears to be designed for ${this.detectIntent(processedPrompt)}. The structure suggests you're looking for a response that combines creativity with practical application.\n\n**Recommendations:**\n1. Consider adding more context about your target audience\n2. Specify the desired output format (list, paragraph, dialogue, etc.)\n3. Include any constraints or preferences you have\n\n**Simulated AI Response:**\nThank you for the prompt! I've analyzed your request and here's my simulated response. In a real implementation, this would be generated by an AI model like GPT-4 or Claude. The mock response demonstrates that the prompt was received and processed correctly.`,

      `Mock AI Response Generator\n\nInput Prompt: "${processedPrompt}"\n\nVariables Detected: ${input.variables ? Object.keys(input.variables).length : 0}\nProcessing Time: ${Math.floor(Math.random() * 500)}ms\n\nGenerated Response:\n---\nHello! I'm a simulated AI response. Your prompt about "${processedPrompt.slice(0, 30)}..." has been received.\n\nIn a production environment, this would be connected to OpenAI, Anthropic, or another AI provider. For now, enjoy this mock response that demonstrates the pipeline is working correctly!\n\nKey Features Demonstrated:\n✓ Prompt routing\n✓ Variable substitution\n✓ Response formatting\n✓ Error handling\n---\n`,

      `Playground Execution Result\n\nPrompt Length: ${processedPrompt.length} characters\nCategory: ${this.detectIntent(processedPrompt)}\nComplexity Score: ${this.calculateComplexity(processedPrompt)}\n\nResponse:\n---\nGreetings! This is a simulated response from the Prompt Verse playground.\n\nYour prompt "${processedPrompt.slice(0, 40)}..." demonstrates ${this.getQualityAssessment(processedPrompt)} understanding of prompt engineering.\n\nExpected Output Quality: Good\nSuggested Improvements:\n• Add specific examples\n• Define output constraints\n• Set tone/style guidelines\n---\n`,
    ];

    const selectedResponse = mockResponses[Math.floor(Math.random() * mockResponses.length)];

    return {
      success: true,
      prompt: processedPrompt,
      response: selectedResponse,
      executedAt: new Date().toISOString(),
      mock: true,
    };
  }

  private detectIntent(prompt: string): string {
    const lowerPrompt = prompt.toLowerCase();

    if (
      lowerPrompt.includes('write') ||
      lowerPrompt.includes('create') ||
      lowerPrompt.includes('generate')
    ) {
      return 'content creation';
    }
    if (
      lowerPrompt.includes('explain') ||
      lowerPrompt.includes('what') ||
      lowerPrompt.includes('how')
    ) {
      return 'explanation/education';
    }
    if (
      lowerPrompt.includes('code') ||
      lowerPrompt.includes('programming') ||
      lowerPrompt.includes('function')
    ) {
      return 'code generation';
    }
    if (
      lowerPrompt.includes('analyze') ||
      lowerPrompt.includes('review') ||
      lowerPrompt.includes('evaluate')
    ) {
      return 'analysis';
    }
    if (
      lowerPrompt.includes('list') ||
      lowerPrompt.includes(' brainstorm') ||
      lowerPrompt.includes('ideas')
    ) {
      return 'brainstorming';
    }

    return 'general purpose';
  }

  private calculateComplexity(prompt: string): string {
    const wordCount = prompt.split(/\s+/).length;
    const hasVariables = prompt.includes('{{');
    const hasConstraints =
      prompt.includes('must') || prompt.includes('should') || prompt.includes('need');

    if (wordCount > 100 && hasVariables && hasConstraints) {
      return 'High';
    }
    if (wordCount > 50 || hasVariables) {
      return 'Medium';
    }
    return 'Low';
  }

  private getQualityAssessment(prompt: string): string {
    const wordCount = prompt.split(/\s+/).length;
    const hasContext = prompt.length > 50;
    const hasStructure = prompt.includes(':') || prompt.includes('\n');

    if (wordCount > 30 && hasContext && hasStructure) {
      return 'a strong';
    }
    if (wordCount > 15) {
      return 'a good';
    }
    return 'a basic';
  }
}

export const playgroundService = new PlaygroundService();
